_default:
	@just --list --unsorted --list-heading '' --list-prefix '—— '

objects := "src/main.c \
src/heap.c \
src/linked_list.c \
src/vec.c"

cflags := "-Wall -Wextra -Wvla -pedantic"
cflags_debug := "-g -fsanitize=address"

build:
    cc {{cflags}} {{cflags_debug}} -o structs {{objects}}
    @echo Built 'structs'!

run: build
    @./structs

clean:
    rm -f ./structs ./rstructs
